### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by pylover** [JKhakpour/virastar.py#1]
First of all. thanks for the project.

I'm interested to know what is the next plan for this project and how to contribute?

**Comment by JKhakpour** [comment]
Hi @pylover ,
For this project I have nothing to do more :) (unless there are some issues need fixing or any suggestion to make it easier to use)

But I will push another project in next weeks which is a simple and configurable text pipeline.
That project's first example config file is this project's pipeline (as a configurable json file not a hard coded pipeline).

I would appreciate hearing your opinion about that code when it pushed on github :)
