### ISSUE TITLE
Coveralls.io

### ISSUE THREAD

**Issue by pylover** [JKhakpour/virastar.py#7]
Please enable the repo in the coveralls.io and put the token here

**Comment by JKhakpour** [comment]
Hi Vahid, 
Coveralls.io says I should not publish the token in public and it can detect github's public repos without token. But it looks like there's something wrong on .travis.yml file. 
Could you please take a look at this file? I can send the token by email if needed.

**Comment by pylover** [comment]
Ok ,We'll try without the token.

**Comment by JKhakpour** [comment]
seems working now!
